[tool.black]
line-length = 100
extend-exclude = "alembic"
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [
  "alembic",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = [
  "E203",
]
